package main.java;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adityasrinivasan' at '6/2/16 7:36 PM' with Gradle 2.13
 *
 * @author adityasrinivasan, @date 6/2/16 7:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
