package test.java;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

import main.java.Library;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'adityasrinivasan' at '6/2/16 7:36 PM' with Gradle 2.13
 *
 * @author adityasrinivasan, @date 6/2/16 7:36 PM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
